version: "3.9"

services:
  db:
    image: postgres:16
    container_name: subscription-db
    restart: always
    environment:
      POSTGRES_USER: subscription_user
      POSTGRES_PASSWORD: subscription_password
      POSTGRES_DB: subscription_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
